global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'usuarios-service'
    static_configs:
      - targets: ['usuarios-service:8001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'posts-service'
    static_configs:
      - targets: ['posts-service:8002']
    metrics_path: /metrics
    scrape_interval: 10s
